site_name: Trabalho Databricks 

nav:
  - Início: index.md
  - Landing Layer: landing.md
  - Bronze Layer: bronze.md
  - Silver Layer: silver.md
  - Gold Layer: gold.md
  - Automação: automacao.md
  - Conclusão: conclusao.md